language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

install: composer install

addons:
  code_climate:
    repo_token: 054b93b8b125197a8c889956f23c8342eed9802490acddc983f6813a00ade410

after_script:
  - vendor/bin/test-reporter
